#:schema https://raw.githubusercontent.com/lapce/lapce/master/extra/schemas/color-theme.json
[color-theme]
name = "Catppuccin Latte"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0


[color-theme.base]
black = "#5C5F77"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
grey = "#E5E5E6"
magenta = "#EA76CB"
orange = "#D19A66"
purple = "#8839ef"
red = "#D20F39"
white = "#ACB0BE"
yellow = "#DF8E1D"

[color-theme.syntax]
"comment" = "#8c8fa1"
"constant" = "#fe640b"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$yellow"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"

"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"

"keyword" = "$purple"
"selfKeyword" = "$purple"

"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"

"string" = "$green"
"string.escape" = "$cyan"

"type.builtin" = "#179299"
"builtinType" = "#179299"
"escape" = "#179299"
"embedded" = "#179299"

"punctuation.delimiter" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
"text.reference" = "$yellow"
"variable" = "$red"
"variable.other.member" = "$green"
"tag" = "$blue"


[color-theme.ui]
"lapce.error" = "$red"
"lapce.warn" = "#E9A700"
"lapce.dropdown_shadow" = "#B4B4B4"
"lapce.border" = "#B4B4B4"
"lapce.scroll_bar" = "#9ca0b0"

"lapce.button.primary.background" = "$green"
"lapce.button.primary.foreground" = "$white"

# tab
"lapce.tab.active.background" = "#e6e9ef"
"lapce.tab.active.foreground" = "$black"
"lapce.tab.active.underline" = "#528BFF"

"lapce.tab.inactive.background" = "#e6e9ef"
"lapce.tab.inactive.foreground" = "$black"
"lapce.tab.inactive.underline" = "#528BFF77"

"lapce.tab.separator" = "#B4B4B4"

"lapce.icon.active" = "$black"
"lapce.icon.inactive" = "#A0A1A7"

"lapce.remote.local" = "#4078F2"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"

"lapce.plugin.name" = "#444444"
"lapce.plugin.description" = "$black"
"lapce.plugin.author" = "#707070"


"terminal.cursor" = "#dc8a78"
"terminal.foreground" = "#4c4f69"
"terminal.background" = "#eff1f5"
"terminal.white" = "#acb0be"
"terminal.black" = "#5c5f77"
"terminal.red" = "#d20f39"
"terminal.blue" = "#1e66f5"
"terminal.green" = "#40a02b"
"terminal.yellow" = "#df8e1d"
"terminal.cyan" = "#179299"
"terminal.magenta" = "#ea76cb"
"terminal.bright_white" = "#bcc0cc"
"terminal.bright_red" = "#d20f39"
"terminal.bright_blue" = "#1e66f5"
"terminal.bright_green" = "#40a02b"
"terminal.bright_yellow" = "#df8e1d"
"terminal.bright_cyan" = "#179299"
"terminal.bright_magenta" = "#ea76cb"
"terminal.bright_black" = "#6c6f85"

"editor.background" = "#eff1f5"
"editor.foreground" = "#4c4f69"
"editor.dim" = "#8c8fa1"
"editor.focus" = "#000000"
"editor.caret" = "#526FFF"
"editor.selection" = "#acb0be"
"editor.current_line" = "#E4E4E6"
"editor.link" = "#dc8a78"
"editor.visible_whitespace" = "$grey"
"editor.indent_guide" = "$grey"
"editor.drag_drop_background" = "#79c1fc33"
"editor.drag_drop_tab_background" = "#0b0e1433"
"editor.sticky_header_background" = "$grey"

"inlay_hint.foreground" = "#bcc0cc"
"inlay_hint.background" = "#e6e9ef"

"error_lens.error.foreground" = "$red"
"error_lens.error.background" = "#E4564920"
"error_lens.warning.foreground" = "$yellow"
"error_lens.warning.background" = "#C1840120"
"error_lens.other.foreground" = "#A0A1A7"
"error_lens.other.background" = "#A0A1A720"

"source_control.added" = "#50A14F32"
"source_control.removed" = "#FF526632"
"source_control.modified" = "#0184BC32"

"palette.background" = "#EAEAEB"
"palette.foreground" = "$black"
"palette.current.background" = "#DBDBDC"
"palette.current.foreground" = "$black"

"completion.background" = "#e6e9ef"
"completion.current" = "#acb0be"

"hover.background" = "#eff1f5"

"activity.background" = "#e6e9ef"
"activity.current" = "#dc8a78"

"panel.background" = "#e6e9ef"
"panel.foreground" = "#4c4f69"
"panel.foreground.dim" = "#A0A1A7"
"panel.current.background" = "#DBDBDC"
"panel.current.foreground" = "#4c4f69"
"panel.current.foreground.dim" = "#A0A1A7"
"panel.hovered.background" = "#E4E4E6"
"panel.hovered.foreground" = "#4c4f69"
"panel.hovered.foreground.dim" = "#A0A1A7"

"status.background" = "#e6e9ef"
"status.foreground" = "$black"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$white"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$white"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$white"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$white"



"markdown.blockquote" = "#686868"
