#:schema https://raw.githubusercontent.com/lapce/lapce/master/extra/schemas/color-theme.json
[color-theme]
name = "Catppuccin Macchiato"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

# https://github.com/catppuccin/catppuccin
# rosewater = "#f4dbd6"
# flamigo = "#f0c6c6"
# pink = "#f5bde6"
# mauve = "#c6a0f6"
# red = "#ed8796"
# maroon = "#ee99a0"
# peach = "#f5a97f"
# yellow = "#eed49f"
# green = "#a6da95"
# teal = "#8bd5ca"
# sky = "#91d7e3"
# sapphire = "#7dc4e4"
# blue = "#8aadf4"
# lavender = "#b7bdf8"
# text = "#cad3f5"
# subtext1 = "#b8c0e0"
# subtext0 = "#a5adcb"
# overlay2 = "#939ab7"
# overlay1 = "#8087a2"
# overlay0 = "#6e738d"
# surface2 = "#5b6078"
# surface1 = "#363a4f"
# surface0 = "#414559"
# base = "#24273a"
# mantle = "#1e2030"
# crust = "#181926"

[color-theme.base]

black = "#494D64"   # surface1
blue = "#8AADF4"    # blue
cyan = "#8BD5CA"    # teal
green = "#A6DA95"   # green
magenta = "#F5BDE6" # pink
orange = "#f5a97f"  # peach
purple = "#c6a0f6"  # mauve
red = "#ed8796"     # red
white = "#B8C0E0"   # subtext1
yellow = "#EED49F"  # yellow


[color-theme.syntax]
"comment" = "#8087a2"
"constant" = "#eed49f"
"type" = "#eed49f"
"typeAlias" = "#eed49f"
"number" = "#eed49f"
"enum" = "#eed49f"
"struct" = "#eed49f"
"structure" = "#eed49f"
"interface" = "#eed49f"
"attribute" = "#eed49f"
"constructor" = "#eed49f"
"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"
"keyword" = "#c6a0f6"
"selfKeyword" = "#c6a0f6"
"field" = "#ed8796"
"property" = "#ed8796"
"enumMember" = "#ed8796"
"enum-member" = "#ed8796"
"variable.other.member" = "#ed8796"
"string" = "$green"
"type.builtin" = "#bbd5ca"
"builtinType" = "#bbd5ca"
"escape" = "#bbd5ca"
"embedded" = "#bbd5ca"

[color-theme.ui]
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#1e2030"
"lapce.border" = "#1e2030"
"lapce.scroll_bar" = "#6e738d"

"lapce.button.primary.background" = "$green"
"lapce.button.primary.foreground" = "$black"

# tab
"lapce.tab.active.background" = "#1e2030"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "$blue"

"lapce.tab.inactive.background" = "#1e2030"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#528BFF77"

"lapce.tab.separator" = ""

"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#5C6370"

"lapce.remote.local" = "#4078F2"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"

"lapce.plugin.name" = "#DDDDDD"
"lapce.plugin.description" = "$white"
"lapce.plugin.author" = "#B0B0B0"


"editor.background" = "#24273a"
"editor.foreground" = "#cad3f5"
"editor.dim" = "#8087a2"
"editor.focus" = "#CCCCCC"
"editor.caret" = "#8bd5ca"
"editor.selection" = "#5b6078"
"editor.current_line" = "#2C313C"
"editor.link" = "#f4dbd6"
"editor.visible_whitespace" = "$grey"
"editor.indent_guide" = "$grey"
"editor.drag_drop_background" = "#79c1fc55"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.sticky_header_background" = "$black"

"inlay_hint.foreground" = "#494d64"
"inlay_hint.background" = "#1e2030"

"source_control.added" = "##a6d18932"
"source_control.removed" = "#ea999c32"
"source_control.modified" = "#8caaee32"

"palette.background" = "#24273a"
"palette.current" = "#5b6078"

"completion.background" = "#24273a"
"completion.current" = "#5b6078"

"hover.background" = "#24273a"

"activity.background" = "#181926"
"activity.current" = "#00000000"

"panel.background" = "#1e2030"
"panel.foreground" = "#cad3f5"
"panel.foreground.dim" = "#A0A1A7"
"panel.current.background" = "#181926"
"panel.current.foreground" = "#cad3f5"
"panel.current.foreground.dim" = "#A0A1A7"
"panel.hovered.background" = "#181926"
"panel.hovered.foreground" = "$black"
"panel.hovered.foreground.dim" = "#A0A1A7"

"status.background" = "#1e2030"
"status.foreground" = "$white"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"



"markdown.blockquote" = "#a5adcb"

"terminal.cursor" = "#f4dbd6"
"terminal.foreground" = "#cad3f5"
"terminal.background" = "#24273a"
"terminal.white" = "#a5adcb"
"terminal.black" = "#494d64"
"terminal.red" = "#ed8796"
"terminal.blue" = "#8aadf4"
"terminal.green" = "#ebff87"
"terminal.yellow" = "#eed49f"
"terminal.cyan" = "#bbd5ca"
"terminal.magenta" = "#c6a0f6"
"terminal.bright_white" = "#bbc0e0"
"terminal.bright_red" = "#ed8796"
"terminal.bright_blue" = "#8aadf4"
"terminal.bright_green" = "#rbff87"
"terminal.bright_yellow" = "#eed49f"
"terminal.bright_cyan" = "#bbd5ca"
"terminal.bright_magenta" = "#c6a0f6"
"terminal.bright_black" = "#586078"
