#:schema https://raw.githubusercontent.com/lapce/lapce/master/extra/schemas/color-theme.json
[color-theme]
name = "Catppuccin Mocha"

[ui]
font-family = ""
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0

# for color reference
# rosewater = "#f5e0dc"
# flamigo = "#f2cdcd"
# pink = "#f5c2e7"
# mauve = "#cba6f7"
# maroon = "#eba0ac"
# peach = "#fab387"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# lavender = "#b4befe"
# text = "#cdd6f4"
# subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
# overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
# surface1 = "#45475a"
# surface0 = "#313244"
# base = "#1e1e2e"
# mantle = "#181825"
# crust = "#11111b"

[color-theme.base]

black = "#45475A"   # surface1
blue = "#89b4fa"    # blue
cyan = "#94E2D5"    # teal
green = "#A6E3A1"   # green
magenta = "#F5C2E7" # pink
orange = "#fab387"  # peach
purple = "#cba6f7"  # mauve
red = "#F38BA8"     # red
white = "#BAC2DE"   # subtext1
yellow = "#F9E2AF"  # yellow

[color-theme.syntax]
"comment" = "#6c7086" #overlay0
"constant" = "#fab387" #peach
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$yellow"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "#74c7ec" #sapphire

"function" = "$blue"
"method" = "$blue"
"function.method" = "#cba6f7"

"keyword" = "#cba6f7" #mauve
"selfKeyword" = "$purple"

"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"

"string" = "$green"
"string.escape" = "$cyan"

"type.builtin" = "$red" #teal
"builtinType" = "$red"  #teal
"escape" = "#94e2d5"       #teal
"embedded" = "#94e2d5"     #teal

"punctuation.delimiter" = "#9399b2" #overlay2
"text.title" = "$orange"
"text.uri" = "$cyan"
"text.reference" = "$yellow"
"variable" = "$red"
"variable.other.member" = "$green"
"tag" = "#cba6f7" #mauve


[color-theme.ui]
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#585b70" #surface2
"lapce.border" = "#585b70"
"lapce.scroll_bar" = "#313244" #surface0

"lapce.button.primary.background" = "#cba6f7" #mauve
"lapce.button.primary.foreground" = "#1e1e2e" #base

# tab
"lapce.tab.active.background" = "#1e1e2e" #base
"lapce.tab.active.foreground" = "#cba6f7"
"lapce.tab.active.underline" = "#cba6f7"

"lapce.tab.inactive.background" = "#1e1e2e" #base
"lapce.tab.inactive.foreground" = "#a6adc8"
"lapce.tab.inactive.underline" = "#a6adc8"

"lapce.tab.separator" = "#11111b"

"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#5C6370"

"lapce.remote.icon" = "$purple"
"lapce.remote.local" = "#11111b"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"

"lapce.plugin.name" = "#DDDDDD"
"lapce.plugin.description" = "$white"
"lapce.plugin.author" = "#B0B0B0"


"editor.background" = "#1e1e2e"
"editor.foreground" = "#cdd6f4"
"editor.dim" = "#7f849c"
"editor.focus" = "#CCCCCC"
"editor.caret" = "#94e2d5"
"editor.selection" = "#585b70"
"editor.current_line" = "#2C313C"
"editor.link" = "#f5e0dc"
"editor.visible_whitespace" = "$grey"
"editor.indent_guide" = "$grey"
"editor.drag_drop_background" = "#79c1fc55"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.sticky_header_background" = "$black"

"inlay_hint.foreground" = "#45475a"
"inlay_hint.background" = "#181825"

"source_control.added" = "##a6d18932"
"source_control.removed" = "#ea999c32"
"source_control.modified" = "#8caaee32"

"palette.background" = "#1e1e2e"
"palette.current" = "#11111b"

"completion.background" = "#1e1e2e"
"completion.current" = "#585b70"

"hover.background" = "#1e1e2e"

"activity.background" = "#181825"
"activity.current" = "#11111b"


"debug.breakpoint" = "$red"
"debug.breakpoint.hover" = "$grey"

"panel.background" = "#181825"
"panel.foreground" = "#cdd6f4"
"panel.foreground.dim" = "#A0A1A7"
"panel.current.background" = "#11111b"
"panel.current.foreground" = "#cdd6f4"
"panel.current.foreground.dim" = "#A0A1A7"
"panel.hovered.background" = "#11111b"
"panel.hovered.active.background" = "#5C6370"
"panel.hovered.foreground" = "#cdd6f4"
"panel.hovered.foreground.dim" = "#A0A1A7"

"status.background" = "#181825"
"status.foreground" = "$white"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"


"markdown.blockquote" = "#a6adc8"

"terminal.cursor" = "#f5e0dc"
"terminal.foreground" = "#cdd6f4"
"terminal.background" = "#1e1e2e"
"terminal.white" = "#bac2de"
"terminal.black" = "#45475a"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "#94e2d5"           #teal
"terminal.magenta" = "#f5c2e7"
"terminal.bright_white" = "#a6adc8"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "#94e2d5"    #teal
"terminal.bright_magenta" = "#f5c2e7" #pink
"terminal.bright_black" = "#585b70"   #surface2
